version: "3.7"

services:
  cosmo_roll_over:
    build: ./cosmo
    container_name: cosmo_roll_over
    working_dir: /frontend
    command: node build
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - landing_mongo
    environment:
      - DEV_MODE=false
  cosmo_roll_over_1:
    build: ./cosmo
    container_name: cosmo_roll_over_1
    working_dir: /frontend
    command: node build
    restart: unless-stopped
    ports:
      - "3002:3000"
    env_file:
      - .env
    depends_on:
      - landing_mongo
    environment:
      - DEV_MODE=false    

  landing_mongo:
    image: mongo
    container_name: landing_mongo
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "./data:/data/db"
  landing_roll_over:
    build: ./landing
    container_name: landing_roll_over
    working_dir: /frontend
    command: node build
    restart: unless-stopped
    ports:
      - "3011:3000"
    env_file:
      - .env
    depends_on:
      - landing_mongo
    environment:
      - DEV_MODE=false
  landing_roll_over_1:
    build: ./landing
    container_name: landing_roll_over_1
    working_dir: /frontend
    command: node build
    restart: unless-stopped
    ports:
      - "3012:3000"
    env_file:
      - .env
    depends_on:
      - landing_mongo
    environment:
      - DEV_MODE=false
  
  preview_generator:
    build: ./apps/preview-generator
    container_name: preview_generator
    command: uvicorn main:app --host 0.0.0.0
    working_dir: /backend/src
  mongo_express:
    image: mongo-express
    env_file:
      - .env
    depends_on:
      - landing_mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:8088:8081"

  denta_roll_over:
    build: ./denta
    container_name: denta_roll_over
    working_dir: /frontend
    command: node build
    restart: unless-stopped
    ports:
      - "3031:3000"
    env_file:
      - .env
    depends_on:
      - landing_mongo
    environment:
      - DEV_MODE=false
      - PUBLIC_APP_NAME=denta
  denta_roll_over_1:
    build: ./denta
    container_name: denta_roll_over_1
    working_dir: /frontend
    command: node build
    restart: unless-stopped
    ports:
      - "3032:3000"
    env_file:
      - .env
    depends_on:
      - landing_mongo
    environment:
      - DEV_MODE=false
      - PUBLIC_APP_NAME=denta

  femida_roll_over:
    build: ./denta
    container_name: femida_roll_over
    working_dir: /frontend
    command: node build
    restart: unless-stopped
    ports:
      - "3041:3000"
    env_file:
      - .env
    depends_on:
      - landing_mongo
    environment:
      - DEV_MODE=false
      - PUBLIC_APP_NAME=femida
  femida_roll_over_1:
    build: ./denta
    container_name: femida_roll_over_1
    working_dir: /frontend
    command: node build
    restart: unless-stopped
    ports:
      - "3042:3000"
    env_file:
      - .env
    depends_on:
      - landing_mongo
    environment:
      - DEV_MODE=false
      - PUBLIC_APP_NAME=femida

  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9900"
    restart: unless-stopped
    ports:
      - "127.0.0.1:9900:9900"
      - "127.0.0.1:9001:9001"
    volumes:
      - "./minio_data:/data"
    environment:
      - MINIO_ROOT_USER=your_username
      - MINIO_ROOT_PASSWORD=your_pasword
      - MINIO_DEFAULT_BUCKETS=femida,landing,denta
