version: "3.7"

services:
  landing_roll_over_dev:
    build:
      context: ./landing
      dockerfile: Dockerfile.dev
    container_name: landing_roll_over_dev
    command: pnpm run dev --host

    working_dir: /frontend
    volumes:
      - ./landing/.svelte-kit/:/frontend/.svelte-kit/
      - ./landing/patches/:/frontend/patches/
      - ./landing/scripts/:/frontend/scripts/
      - ./landing/src/:/frontend/src/
      - ./landing/static/:/frontend/static/
      - ./landing/package.json:/frontend/package.json
      - ./landing/pnpm-lock.yaml:/frontend/pnpm-lock.yaml
      - ./landing/postcss.config.cjs:/frontend/postcss.config.cjs
      - ./landing/svelte.config.js:/frontend/svelte.config.js
      - ./landing/tailwind.config.cjs:/frontend/tailwind.config.cjs
      - ./landing/vite.config.ts:/frontend/vite.config.ts
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - DEV_MODE=true
    depends_on:
      - landing_mongo_dev
  denta_dev:
    build:
      context: ./denta
      dockerfile: Dockerfile.dev
    container_name: denta_dev
    command: pnpm run dev --host

    working_dir: /frontend
    volumes:
      - ./denta/.svelte-kit/:/frontend/.svelte-kit/
      - ./denta/patches/:/frontend/patches/
      - ./denta/scripts/:/frontend/scripts/
      - ./denta/src/:/frontend/src/
      - ./denta/static/:/frontend/static/
      - ./denta/package.json:/frontend/package.json
      - ./denta/pnpm-lock.yaml:/frontend/pnpm-lock.yaml
      - ./denta/postcss.config.cjs:/frontend/postcss.config.cjs
      - ./denta/svelte.config.js:/frontend/svelte.config.js
      - ./denta/tailwind.config.cjs:/frontend/tailwind.config.cjs
      - ./denta/vite.config.ts:/frontend/vite.config.ts
    ports:
      - "5174:5173"
    env_file:
      - .env
    environment:
      - DEV_MODE=true
      - PUBLIC_APP_NAME=denta
    depends_on:
      - landing_mongo_dev

  femida_dev:
    build:
      context: ./denta
      dockerfile: Dockerfile.dev
    container_name: femida_dev
    command: pnpm run dev --host

    working_dir: /frontend
    volumes:
      - ./denta/.svelte-kit/:/frontend/.svelte-kit/
      - ./denta/patches/:/frontend/patches/
      - ./denta/scripts/:/frontend/scripts/
      - ./denta/src/:/frontend/src/
      - ./denta/static/:/frontend/static/
      - ./denta/package.json:/frontend/package.json
      - ./denta/pnpm-lock.yaml:/frontend/pnpm-lock.yaml
      - ./denta/postcss.config.cjs:/frontend/postcss.config.cjs
      - ./denta/svelte.config.js:/frontend/svelte.config.js
      - ./denta/tailwind.config.cjs:/frontend/tailwind.config.cjs
      - ./denta/vite.config.ts:/frontend/vite.config.ts
    ports:
      - "5175:5173"
    env_file:
      - .env
    environment:
      - DEV_MODE=true
      - PUBLIC_APP_NAME=femida
    depends_on:
      - landing_mongo_dev
  landing_mongo_dev:
    image: mongo
    container_name: landing_mongo_dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "./data:/data/db"
  mongo_express:
    image: mongo-express
    env_file:
      - .env
    depends_on:
      - landing_mongo_dev
    restart: unless-stopped
    ports:
      - "127.0.0.1:8088:8081"
  preview_generator_dev:
    build: ./apps/preview-generator
    container_name: preview_generator_dev
    command: uvicorn main:app --host 0.0.0.0
    working_dir: /backend/src
    ports:
      - "8001:8000"
    volumes:
      - ./apps/preview-generator/src:/backend/src
      - ./apps/preview-generator/requirements.txt:/backend/requirements.txt
  minio-dev:
    image: quay.io/minio/minio
    container_name: minio-dev
    command: server /data --console-address ":9900"
    ports:
      - "9900:9900"
      - "9001:9001"
    volumes:
      - "./minio_data:/data"
    environment:
      - MINIO_ROOT_USER=your_username
      - MINIO_ROOT_PASSWORD=your_pasword
      - MINIO_DEFAULT_BUCKETS=your_bucket_name
