version: "3.7"

services:
  landing_mongo:
    image: mongo
    container_name: landing_mongo
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "./data:/data/db"
  landing_roll_over:
    build: ./landing
    container_name: landing_roll_over
    working_dir: /frontend
    command: node build
    restart: unless-stopped
    ports:
      - "3011:3000"
    env_file:
      - .env
    depends_on:
      - landing_mongo
    environment:
      - DEV_MODE=false
  landing_roll_over_1:
    build: ./landing
    container_name: landing_roll_over_1
    working_dir: /frontend
    command: node build
    restart: unless-stopped
    ports:
      - "3012:3000"
    env_file:
      - .env
    depends_on:
      - landing_mongo
    environment:
      - DEV_MODE=false
  preview_generator:
    build: ./apps/preview-generator
    container_name: preview_generator
    command: uvicorn main:app --host 0.0.0.0
    working_dir: /backend/src
  mongo_express:
    image: mongo-express
    env_file:
      - .env
    depends_on:
      - landing_mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:8088:8081"

  denta_roll_over:
    build: ./denta
    container_name: denta_roll_over
    working_dir: /frontend
    command: node build
    restart: unless-stopped
    ports:
      - "3031:3000"
    env_file:
      - .env
    depends_on:
      - landing_mongo
    environment:
      - DEV_MODE=false
      - APP_NAME=denta
  denta_roll_over_1:
    build: ./denta
    container_name: denta_roll_over_1
    working_dir: /frontend
    command: node build
    restart: unless-stopped
    ports:
      - "3032:3000"
    env_file:
      - .env
    depends_on:
      - landing_mongo
    environment:
      - DEV_MODE=false
      - APP_NAME=denta

  femida_roll_over:
    build: ./denta
    container_name: femida_roll_over
    working_dir: /frontend
    command: node build
    restart: unless-stopped
    ports:
      - "3041:3000"
    env_file:
      - .env
    depends_on:
      - landing_mongo
    environment:
      - DEV_MODE=false
      - PUBLIC_APP_NAME=femida
  femida_roll_over_1:
    build: ./denta
    container_name: femida_roll_over_1
    working_dir: /frontend
    command: node build
    restart: unless-stopped
    ports:
      - "3042:3000"
    env_file:
      - .env
    depends_on:
      - landing_mongo
    environment:
      - DEV_MODE=false
      - PUBLIC_APP_NAME=femida
