version: "3.7"

services:
  landing_roll_over_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: landing_roll_over_dev
    command: pnpm run dev --host

    working_dir: /frontend
    volumes:
      - ./.svelte-kit/:/frontend/.svelte-kit/
      - ./patches/:/frontend/patches/
      - ./scripts/:/frontend/scripts/
      - ./src/:/frontend/src/
      - ./static/:/frontend/static/
      - ./package.json:/frontend/package.json
      - ./pnpm-lock.yaml:/frontend/pnpm-lock.yaml
      - ./postcss.config.cjs:/frontend/postcss.config.cjs
      - ./svelte.config.js:/frontend/svelte.config.js
      - ./tailwind.config.cjs:/frontend/tailwind.config.cjs
      - ./vite.config.ts:/frontend/vite.config.ts
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - DEV_MODE=true
  landing_mongo_dev:
    image: mongo
    container_name: landing_mongo_dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "./data:/data/db"
  mongo_express:
    image: mongo-express
    env_file:
      - .env
    depends_on:
      - landing_mongo_dev
    restart: unless-stopped
    ports:
      - "8088:8081"
  preview_generator_dev:
    build: ./apps/preview-generator
    container_name: preview_generator_dev
    command: uvicorn main:app --host 0.0.0.0
    working_dir: /backend/src