export const en = {
  "denta-crm": "denta-crm",
  "Система управления стоматологической клиникой, создание сайта для стоматологии и поиск клиник.":
    "System for managing a dental clinic, creating a website for dentistry and searching for clinics.",
  "Система управления стоматологической клиникой": "System for managing a dental clinic",
  "Что такое denta-crm?": "What is denta-crm?",
  "denta-crm - это система управления стоматологической клиникой, которая позволяет вам управлять клиникой, а также взаимодействовать с пациентами.":
    "denta-crm is a system for managing a dental clinic that allows you to manage a clinic and interact with patients.",
  "denta-crm - это больше чем crm": "denta-crm is more than crm",
  "denta-crm - это еще и система создания сайтов для стоматологических клиник, которая позволяет вам создать сайт для вашей клиники, а также взаимодействовать с пациентами.":
    "denta-crm is also a system for creating websites for dental clinics that allows you to create a website for your clinic and interact with patients.",
  "Создать компанию": "Create a company",
  "Какие возможности есть в denta-crm?": "What are the features of denta-crm?",
  "denta-crm позволяет вам управлять клиникой, а также взаимодействовать с пациентами. В denta-crm есть следующие возможности:":
    "denta-crm allows you to manage a clinic and interact with patients. denta-crm has the following features:",
  "Управление клиникой": "Clinic management",
  "Взаимодействие с пациентами": "Interaction with patients",
  "Создание сайта для клиники": "Creating a website for a clinic",
  "denta-crm - это база всех стоматологических клиник, которые есть в мире.":
    "denta-crm is a database of all dental clinics in the world.",
  "Найти клинику в denta-crm можно в разделе": "You can find a clinic in denta-crm in the section",
  "Поиск стоматологий по странам": "Search for dentists by country",
  "Поиск стоматологий в вашей стране по базе denta-crm":
    "Search for dentists in your country in the denta-crm database",
  "На данный момент в базе denta-crm есть информация о стоматологиях в следующих странах":
    "At the moment, the denta-crm database contains information about dentists in the following countries:",
  "Мы постоянно работаем над тем, чтобы наша база была максимально полной и актуальной.":
    "We are constantly working to make our database as complete and up-to-date as possible.",
  "Поиск стоматологий по стране": "Search for dentists by country",
  поиск: "search",

  Поиск: "Search",
  Статьи: "Articles",
  Кошелек: "Wallet",
  Контакты: "Contacts",
  Компания: "Company",
  "О нас": "About us",
  Записи: "Appointments",
  Пациенты: "Patients",
  Кабинеты: "Cabinets",
  Доктора: "Doctors",
  "Прайс-лист": "Price list",
  Подписка: "Subscription",
  Транзакции: "Transactions",
  Пополнить: "Top up",
  "Публичная страница": "Public page",
  Владелец: "Owner",
  "Дата создания": "Creation date",
  "Нет контактов": "No contacts",

  Улица: "Street",
  Дом: "House",
  "Нет ссылок на карте": "No links on the map",
  Перейти: "Go to",
  "Языки приёма": "Reception languages",
  "Рабочие часы": "Working hours",
  Начало: "Start",
  Конец: "End",
  "Временной шаг": "Time step",
  "Основная валюта": "Main currency",
  "Не выбрано": "Not selected",
  "Удалить компанию": "Delete company",
  "Внимание! Это действие нельзя отменить!": "Attention! This action cannot be undone!",

  "Статьи на denta-crm": "Articles on denta-crm",
  "Разделы профессиональных статей на denta-crm": "Sections of professional articles on denta-crm",
  "Разделы статей на denta-crm": "Sections of articles on denta-crm",
  "Статьи про crm системы для стоматологий": "Articles about crm systems for dentistry",
  "Статьи про услуги в стоматологиях": "Articles about services in dentistry",

  "Поиск стоматологий в": "Search for dentists in",
  "Выберите страну и город:": "Select a country and city:",
  "К сожалению, в этом городе мы не нашли стоматологий":
    "Unfortunately, we did not find dentists in this city",
  "Попробуйте выбрать другой город": "Try choosing another city",
  Адрес: "Address",
  Телефон: "Phone",
  Подробнее: "More",
  "Информация о стоматологии": "Information about the dentist",
  Описание: "Description",
  "Открыть на google карте": "Open on google map",
  Стоматология: "Dentistry",
  в: "in",

  "Другие стоматологии в": "Other dentists in",

  Отзывы: "Reviews",
  "Это Ваш отзыв": "This is your review",
  Удалить: "Delete",
  Редактировать: "Edit",
  "Оставить отзыв": "Leave a review",
  "Ваше имя": "Your name",
  "Войдите, чтобы оставить отзыв": "Log in to leave a review",
  "Ваша оценка": "Your rating",
  "Ваш коментарий": "Your comment",
  "Поставьте оценку": "Rate",
  "Заполните все поля": "Fill in all fields",
  Отправить: "Send",

  Создано: "Created",
  Изменено: "Changed",
  "Не выбрана компания для просмотра": "No company selected to view",
  "Как выбрать компанию?": "How to choose a company?",
  "Пожалуйста, выберите компанию в поиске для просмотра.":
    "Please select a company in the search to view.",
  "Перейти в поиск": "Go to search",
  "Как создать компанию?": "How to create a company?",
  "Если у вас нет компании, то создайте её в соответствующем разделе":
    "If you don't have a company, create it in the appropriate section",
  "Приступить к созданию компании!": "Start creating a company!",
  "Создать команию": "Create a company",
  "Расположение головного офиса или клиники (если одна)":
    "Location of the head office or clinic (if one)",
  "На следующем шаге вы сможете добавить филиалы и кабинеты.":
    "On the next step, you can add branches and offices.",
  Город: "City",
  "Заполните Название": "Fill in the Name",
  "Заполните Страну": "Fill in the Country",
  "Заполните Город": "Fill in the City",
  Создать: "Create",
  Название: "Name",
  Страна: "Country",
  Войти: "Log in",
  Зарегистрироваться: "Sign up",

  "О команде разработки CRM-системы для стоматологов":
    "About the development team of the CRM system for dentists",
  "Сервис создан в гильдии открытых проектов": "The service was created in the open projects guild",
  "Нормативные документы": "Regulatory documents",
  Документы: "Documents",
  "Политика конфиденциальности": "Privacy policy",
  "Пользовательское соглашение": "Terms of Service",
  "Политика в отношении файлов cookie": "Cookie Policy",
  "Обратно к документам": "Back to documents",
  "CRM-система для стоматологий": "CRM system for dentistry",
  "Ваши компании": "Your companies",
  "Ой, кажется у вас до сих пор не создана компания":
    "Oops, it seems you still don't have a company",
  "CRM-система для стоматологов и стоматолгических клиник":
    "CRM system for dentists and dental clinics",
  "Попробуйте бесплатно создать компанию, это займет до 10 минут, и вы сможете управлять своей стоматологией без головной боли в ведении отчетности.":
    "Try to create a company for free, it will take up to 10 minutes, and you will be able to manage your dentistry without a headache in accounting.",
  "А ещё, мы займемся продвижением вашей стоматологии в поиске.":
    "And also, we will promote your dentistry in search.",
  "Создать компанию!": "Create a company!",
  "Почему наша CRM для стоматологов так оптимальна?": "Why is our CRM for dentists so optimal?",
  "Девушка стоматолог за ноутбуком улыбается": "Dentist in front of a laptop smiling",
  "Стоматолог в кресле": "Dentist in a chair",
  "Стоматолог за компьютером": "Dentist at the computer",
  "Зайти в личный кабинет и создать компанию для стоматологии или сети стоматологий в CRM-системе для стоматологов":
    "Log in to your personal account and create a company for dentistry or a network of dentistry in the CRM system for dentists",

  "Что такое denta-crm - CRM система для стоматологий?":
    "What is denta-crm - CRM system for dentists?",
  "О нас - Разработчики denta-crm": "About us - denta-crm developers",
  ...{
    "femida-crm": "femida-crm",
    "Что такое femida-crm?": "What is femida-crm?",
    "Что такое femida-crm - CRM система для юридических компаний?":
      "What is femida-crm - CRM system for law firms?",

    "Система управления юридической компанией, создание сайта для юридической компании и поиск юридических компаний.":
      "System for managing a law firm, creating a website for a law firm and searching for law firms.",

    "femida-crm - это система управления стоматологической клиникой, которая позволяет вам управлять клиникой, а также взаимодействовать с пациентами.":
      "femida-crm is a system for managing a dental clinic that allows you to manage a clinic and interact with patients.",
    "femida-crm - это больше чем crm": "femida-crm is more than crm",
    "femida-crm - это еще и система создания сайтов для стоматологических клиник, которая позволяет вам создать сайт для вашей клиники, а также взаимодействовать с пациентами.":
      "femida-crm is also a system for creating websites for dental clinics that allows you to create a website for your clinic and interact with patients.",

    Уведомления: "Notifications",
    "Название не может быть пустым": "The name cannot be empty",
    "Дата не может быть пустой": "Date cannot be empty",
    "Дата не может быть меньше текущей": "The date cannot be earlier than the current one",
    "Файл не может быть пустым": "The file cannot be empty",
    "Ошибка при загрузке файла": "Error loading file",
    "Ошибка при сохранении контракта": "Error saving contract",
    "Добавить контракт": "Add contract",
    Документ: "Document",
    "Ошибка при удалении файла": "Error deleting file",
    Скачать: "Download",
    "Ошибка при удалении контракта": "Error deleting contract",
    "Вы уверены что хотите удалить?": "Are you sure you want to delete?",
    "Выберите файл": "Select a file",
    "Дата окончания": "End date",
    Загрузить: "Upload",
    Истек: "Expired",
    Действует: "Valid",
    "Дней до окончания": "Days until expiration",
    "Добавить уведомление": "Add notification",
    Неактивно: "Inactive",
    Активно: "Active",
    "Статус уведомления": "Notification status",
    "За сколько дней": "How many days",
    "Сохранить изменения": "Save changes",
    Ожидается: "Expected",
    "CRM-система для юристов": "CRM system for lawyers",
    "Девушка юрист за ноутбуком улыбается": "A lawyer in front of a laptop smiling",
    "Юрист в кресле": "Lawyer in a chair",
  },
} as const;
