export const vacancies = [
  {
    id: "CTO-roll-over",
    title: "СТО",
    company: "roll-over",
    description: "Принятие решений и поддержка команд разработки",
    requirments: ["Технический бекграунд"],
  },
  {
    id: "Project-manager-roll-over",
    title: "Project manager",
    company: "red-flags",
    description: "Управление проектом red-flags",
    requirments: ["Любить людей"],
  },
  {
    id: "Marketing-roll-over",
    title: "Маркетолог",
    company: "roll-over",
    description: "Разработка и реализация стратегии продвижения проектов",
    requirments: ["Желание разобраться в том, как продвигать продукты"],
  },
  {
    id: "SMM-roll-over",
    title: "smm менеджер",
    company: "roll-over",
    description: "Разработка и реализация стратегии продвижения проектов в соц. сетях",
    requirments: ["Желание разобраться в том, как вести соц. сети"],
  },
  {
    id: "Svelte-roll-over",
    title: "Svelte разработчик",
    company: "hide-hire",
    description: 'Разработка сервиса "hide-hire"',
    requirments: ["Желание разобраться в том, как вести соц. сети"],
  },
  {
    id: "Front-end-roll-over",
    title: "Front-end разработчик",
    company: "roll-over",
    description: "Разработка фронтенда для проектов, включая эту страницу",
    requirments: ["Желание научиться писать фронтенд"],
  },
  {
    id: "Shorts-maker-its-open-mic",
    title: "Shorts maker (video)",
    company: "its-open-mic",
    description: "Выделение коротких, но полноценных видео из полных",
    requirments: ["Желание научиться монтировать видео"],
  },
];
